---
title: "Covid19 Data"
author: "Assoc Prof KIM"
date: "3/14/2020"
output: flexdashboard::flex_dashboard
---

Page 1
=============================================================================

Column
------------------------------------------------------------------------------

### Data

Data as of `r Sys.Date()`

```{r}
#devtools::install_github("datadotworld/dwapi-r", build_vignettes = TRUE)
## required to install data.world package
#devtools::install_github("datadotworld/data.world-r", build_vignettes = TRUE)

library(data.world)
library(dwapi)
library(tidyverse)
library(kableExtra)
library(ggiraph)
library(plotly)
```



```{r}
# Connect to data.world
# Get token from data.world
save_cfg <- data.world::save_config("eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyLWFuZC1yLXN0dWRpbzpraW00NTk3IiwiaXNzIjoiY2xpZW50OnItYW5kLXItc3R1ZGlvOmFnZW50OmtpbTQ1OTc6OjIwNDU3ZDUxLWI2YjAtNDE2Yy1hYThkLWYwMTY4NmZiZjYzNSIsImlhdCI6MTU4NDE0NDA5NSwicm9sZSI6WyJ1c2VyX2FwaV9hZG1pbiIsInVzZXJfYXBpX3JlYWQiLCJ1c2VyX2FwaV93cml0ZSJdLCJnZW5lcmFsLXB1cnBvc2UiOnRydWUsInNhbWwiOnt9fQ.C05SW-wZl66PbDlTx9UAIk-tKTBvbROUhHV3euL_0hXdpJ16wg2icauSwmTd4CjnlkcsyoShoZJtwHa83ui1aQ")
data.world::set_config(save_cfg)
```



```{r}

# Read data
# 
# - read URL
# - perform SQL query
# - quick data view


covid19 <- "https://data.world/kim4597/covid19my"
covid19_query <- data.world::qry_sql(paste0(
  "SELECT *",
  "FROM world_covid19"))

covid19.data <- data.world::query(covid19_query, dataset = covid19)
```



```{r}
# Variables in data
# 
# Get the list of variables
#glimpse(covid19.data)
#kable(covid19.data) %>% 
#  kable_styling(bootstrap_options = c("striped", "hover", "responsive"))

### Cars

DT::datatable(covid19.data, options = list(
  pageLength = 15
))

```

Column 
-------------------------------------------------------------------------------

### Plot data for worldwide (Cases)


```{r}
covid19.data.all <- covid19.data %>% filter(location == 'Worldwide')
tot_cases <- covid19.data.all %>%
  group_by(date) %>% 
  count(total_cases)
```

Plot


```{r, fig.width=5, fig.height=5}
plot.tot.cases <- ggplot(tot_cases, aes(x = date, y = total_cases)) +
  geom_line()
ggplotly(plot.tot.cases)
```


### Plot data for worldwide (Deaths)

```{r}
tot_deaths <- covid19.data.all %>%
  group_by(date) %>% 
  count(total_deaths)
plot.tota.deaths <- ggplot(tot_deaths, aes(x = date, y = total_deaths)) +
  geom_line()
ggplotly(plot.tota.deaths)
```

Page 2
==============================================================================


Page 3
=============================================================================


```{r}
library(lubridate)
library(scales)


covid19.data.all <- covid19.data %>% filter(location == 'Worldwide')

stat_month <- covid19.data.all %>% 
  group_by(month=floor_date(date, "month"))
  

cfr_month <- stat_month  %>%
  group_by(month) %>% 
  summarize(CFR = sum(total_deaths)/sum(total_cases))

```


```{r, fig.width=5, fig.height=5}
plot.cfr.month <- ggplot(cfr_month, aes(x = month, y = CFR*1000)) +
  geom_line() +
  scale_x_date(date_breaks = "1 months", date_labels = "%b %Y") +
  ylab("Case Fatality Rate (per 1,000 case per month)")
ggplotly(plot.cfr.month)
```

